# Generated by Django 2.0.6 on 2020-02-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0002_auto_20200219_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/static/img/abcimage.jpg', upload_to='eventImages/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
