# Generated by Django 2.0.6 on 2020-02-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0004_usereventregisteration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default='20:00'),
        ),
    ]
