# Generated by Django 2.0.6 on 2020-02-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0005_auto_20200224_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventType',
            field=models.CharField(default='Others', max_length=255),
        ),
    ]
